require('dotenv').config();

const path = require('path');
const express = require('express');
const helmet = require('helmet');
const cors = require('cors');
const rateLimit = require('express-rate-limit');

const app = express();

// Basic configuration
const PORT = process.env.PORT || 2580;
const SECRET_TOKEN = process.env.SECRET_TOKEN || null;
const JWT_SECRET = process.env.JWT_SECRET || SECRET_TOKEN || 'changeme-jwt-secret';

if (!SECRET_TOKEN) {
  // In production this should be generated by install.sh; warn loudly if missing
  console.warn('[ServerDock] WARNING: SECRET_TOKEN is not set. Login will not work until it is configured in .env.');
}

// Attach config to app locals so routes can use it
app.locals.config = {
  PORT,
  SECRET_TOKEN,
  JWT_SECRET
};

// Middleware
app.use(helmet());
app.use(express.json({ limit: '1mb' }));

// CORS - by default, same-origin only; can be extended later via env
const allowedOrigins = (process.env.CORS_ORIGINS || '').split(',').map(o => o.trim()).filter(Boolean);
app.use(
  cors({
    origin: function (origin, callback) {
      if (!origin) return callback(null, true); // same-origin / curl
      if (allowedOrigins.length === 0 || allowedOrigins.includes(origin)) {
        return callback(null, true);
      }
      return callback(new Error('Not allowed by CORS'));
    },
    credentials: true
  })
);

// Rate limit only login endpoint (mounted later)
const loginLimiter = rateLimit({
  windowMs: 10 * 60 * 1000, // 10 minutes
  max: 5,
  standardHeaders: true,
  legacyHeaders: false
});

// Simple health endpoint (unauthenticated) for uptime monitoring
app.get('/health', (req, res) => {
  res.json({ status: 'ok', uptime: process.uptime() });
});

// API route skeletons
const authRouter = express.Router();
authRouter.post('/login', loginLimiter, (req, res) => {
  // Placeholder implementation; real JWT logic will be added later
  const { token } = req.body || {};
  if (!SECRET_TOKEN) {
    return res.status(500).json({ error: 'Panel is not configured correctly: SECRET_TOKEN is missing.' });
  }
  if (!token || token !== SECRET_TOKEN) {
    return res.status(401).json({ error: 'Invalid token' });
  }
  // To be replaced with real JWT issuance
  return res.json({ message: 'Auth route skeleton OK - JWT implementation pending.' });
});

app.use('/api/auth', authRouter);

// Placeholder routers for future implementation
app.use('/api/system', (req, res) => {
  res.status(501).json({ error: 'System info endpoint not implemented yet.' });
});

app.use('/api/packages', (req, res) => {
  res.status(501).json({ error: 'Packages endpoint not implemented yet.' });
});

app.use('/api/nginx', (req, res) => {
  res.status(501).json({ error: 'Nginx endpoint not implemented yet.' });
});

app.use('/api/pm2', (req, res) => {
  res.status(501).json({ error: 'PM2 endpoint not implemented yet.' });
});

app.use('/api/database', (req, res) => {
  res.status(501).json({ error: 'Database endpoint not implemented yet.' });
});

// Serve frontend (Vite build) from /public when available
const publicDir = path.join(__dirname, 'public');
app.use(express.static(publicDir));

// For SPA routing, serve index.html for unknown routes (except API / health)
app.get('*', (req, res, next) => {
  if (req.path.startsWith('/api') || req.path.startsWith('/health') || req.path.startsWith('/ws')) {
    return next();
  }
  res.sendFile(path.join(publicDir, 'index.html'), (err) => {
    if (err) next(err);
  });
});

// Start server
app.listen(PORT, () => {
  console.log(`[ServerDock] Server listening on port ${PORT}`);
});

