require('dotenv').config();

const path = require('path');
const http = require('http');
const express = require('express');
const helmet = require('helmet');
const cors = require('cors');
const rateLimit = require('express-rate-limit');
const WebSocket = require('ws');
const pty = require('node-pty');

const authMiddleware = require('./src/api/middleware/auth');
const createAuthRouter = require('./src/api/routes/auth');
const systemRouter = require('./src/api/routes/system');
const packagesRouter = require('./src/api/routes/packages');
const nginxRouter = require('./src/api/routes/nginx');
const pm2Router = require('./src/api/routes/pm2');
const databaseRouter = require('./src/api/routes/database');

const app = express();
const server = http.createServer(app);

// Basic configuration
const PORT = process.env.PORT || 2580;
const SECRET_TOKEN = process.env.SECRET_TOKEN || null;
const JWT_SECRET = process.env.JWT_SECRET || SECRET_TOKEN || 'changeme-jwt-secret';

if (!SECRET_TOKEN) {
  // In production this should be generated by install.sh; warn loudly if missing
  console.warn(
    '[ServerDock] WARNING: SECRET_TOKEN is not set. Login will not work until it is configured in .env.'
  );
}

// Attach config to app locals so routes can use it
app.locals.config = {
  PORT,
  SECRET_TOKEN,
  JWT_SECRET
};

// Middleware
app.use(helmet());
app.use(express.json({ limit: '1mb' }));

// CORS - by default, same-origin only; can be extended later via env
const allowedOrigins = (process.env.CORS_ORIGINS || '')
  .split(',')
  .map((o) => o.trim())
  .filter(Boolean);
app.use(
  cors({
    origin: function (origin, callback) {
      if (!origin) return callback(null, true); // same-origin / curl
      if (allowedOrigins.length === 0 || allowedOrigins.includes(origin)) {
        return callback(null, true);
      }
      return callback(new Error('Not allowed by CORS'));
    },
    credentials: true
  })
);

// Rate limit only login endpoint (used inside auth router)
const loginLimiter = rateLimit({
  windowMs: 10 * 60 * 1000, // 10 minutes
  max: 5,
  standardHeaders: true,
  legacyHeaders: false
});

// Simple health endpoint (unauthenticated) for uptime monitoring
app.get('/health', (req, res) => {
  res.json({ status: 'ok', uptime: process.uptime() });
});

// API routes
const authRouter = createAuthRouter(loginLimiter);
app.use('/api/auth', authRouter);

// Protected routes
app.use('/api/system', authMiddleware, systemRouter);
app.use('/api/packages', authMiddleware, packagesRouter);
app.use('/api/nginx', nginxRouter);
app.use('/api/pm2', pm2Router);
app.use('/api/database', databaseRouter);

// Serve frontend (Vite build) from /public when available
const publicDir = path.join(__dirname, 'public');
app.use(express.static(publicDir));

// For SPA routing, serve index.html for unknown routes (except API / health)
app.get('*', (req, res, next) => {
  if (req.path.startsWith('/api') || req.path.startsWith('/health') || req.path.startsWith('/ws')) {
    return next();
  }
  res.sendFile(path.join(publicDir, 'index.html'), (err) => {
    if (err) next(err);
  });
});

// WebSocket terminal: /ws/terminal?token=<JWT>
const wss = new WebSocket.Server({ noServer: true });

function verifyJwt(token, secret) {
  try {
    const jwt = require('jsonwebtoken');
    return jwt.verify(token, secret);
  } catch {
    return null;
  }
}

server.on('upgrade', (request, socket, head) => {
  const { url } = request;
  if (!url || !url.startsWith('/ws/terminal')) {
    socket.destroy();
    return;
  }

  const queryString = url.split('?')[1] || '';
  const params = new URLSearchParams(queryString);
  const token = params.get('token');
  const payload = verifyJwt(token, JWT_SECRET);
  if (!payload) {
    socket.destroy();
    return;
  }

  wss.handleUpgrade(request, socket, head, (ws) => {
    wss.emit('connection', ws, request, payload);
  });
});

wss.on('connection', (ws) => {
  const shell = '/bin/bash';
  const ptyProcess = pty.spawn(shell, [], {
    name: 'xterm-color',
    cols: 80,
    rows: 24,
    cwd: process.env.HOME || '/root',
    env: process.env
  });

  ptyProcess.onData((data) => {
    ws.send(data);
  });

  ws.on('message', (msg) => {
    const text = msg.toString();
    try {
      const maybeJson = JSON.parse(text);
      if (maybeJson && maybeJson.type === 'resize' && maybeJson.cols && maybeJson.rows) {
        ptyProcess.resize(maybeJson.cols, maybeJson.rows);
        return;
      }
    } catch {
      // not JSON, fall through
    }
    ptyProcess.write(text);
  });

  ws.on('close', () => {
    ptyProcess.kill();
  });
});

// Start server
server.listen(PORT, () => {
  console.log(`[ServerDock] Server listening on port ${PORT}`);
});

